export const BIRD_CATALOG = [
  { slug: "american_robin", filename: "american_robin.webp" },
  { slug: "american_woodcock", filename: "american_woodcock.webp" },
  { slug: "australian_magpie", filename: "australian_magpie.webp" },
  { slug: "australian_pied_cormorant", filename: "australian_pied_cormorant.webp" },
  { slug: "barn_swallow", filename: "barn_swallow.webp" },
  { slug: "black_billed_gull", filename: "black_billed_gull.webp" },
  { slug: "black_throated_sparrow", filename: "black_throated_sparrow.webp" },
  { slug: "blue_jay", filename: "blue_jay.webp" },
  { slug: "brown_headed_cowbird", filename: "brown_headed_cowbird.webp" },
  { slug: "brown_thrasher", filename: "brown_thrasher.webp" },
  { slug: "california_quail", filename: "california_quail.webp" },
  { slug: "california_scrub_jay", filename: "california_scrub_jay.webp" },
  { slug: "canadian_goose", filename: "canadian_goose.webp" },
  { slug: "cardinal", filename: "cardinal.webp" },
  { slug: "cedar_waxwing", filename: "cedar_waxwing.webp" },
  { slug: "chaffinch", filename: "chaffinch.webp" },
  { slug: "common_moorhen", filename: "common_moorhen.webp" },
  { slug: "common_wood_pigeon", filename: "common_wood_pigeon.webp" },
  { slug: "coot", filename: "coot.webp" },
  { slug: "curve_billed_thrasher", filename: "curve_billed_thrasher.webp" },
  { slug: "dark_eyed_junco", filename: "dark_eyed_junco.webp" },
  { slug: "downy_woodpecker", filename: "downy_woodpecker.webp" },
  { slug: "eastern_bluebird", filename: "eastern_bluebird.webp" },
  { slug: "eastern_phoebe", filename: "eastern_phoebe.webp" },
  { slug: "eastern_towhee", filename: "eastern_towhee.webp" },
  { slug: "eurasian_blue_tit", filename: "eurasian_blue_tit.webp" },
  { slug: "eurasian_jackdaw", filename: "eurasian_jackdaw.webp" },
  { slug: "eurasian_magpie", filename: "eurasian_magpie.webp" },
  { slug: "eurasian_wren", filename: "eurasian_wren.webp" },
  { slug: "european_goldfinch", filename: "european_goldfinch.webp" },
  { slug: "european_greenfinch", filename: "european_greenfinch.webp" },
  { slug: "european_herring_gull", filename: "european_herring_gull.webp" },
  { slug: "european_robin", filename: "european_robin.webp" },
  { slug: "gila_woodpecker", filename: "gila_woodpecker.webp" },
  { slug: "gray_catbird", filename: "gray_catbird.webp" },
  { slug: "great_blue_heron", filename: "great_blue_heron.webp" },
  { slug: "grey_heron", filename: "grey_heron.webp" },
  { slug: "hooded_crow", filename: "hooded_crow.webp" },
  { slug: "house_finch", filename: "house_finch.webp" },
  { slug: "house_sparrow", filename: "house_sparrow.webp" },
  { slug: "kaka", filename: "kaka.webp" },
  { slug: "killdeer", filename: "killdeer.webp" },
  { slug: "kingfisher", filename: "kingfisher.webp" },
  { slug: "muscovy_duck", filename: "muscovy_duck.webp" },
  { slug: "mute_swan", filename: "mute_swan.webp" },
  { slug: "new_zealand_bellbird", filename: "new_zealand_bellbird.webp" },
  { slug: "new_zealand_pigeon", filename: "new_zealand_pigeon.webp" },
  { slug: "northern_mockingbird", filename: "northern_mockingbird.webp" },
  { slug: "pileated_woodpecker", filename: "pileated_woodpecker.webp" },
  { slug: "pine_warbler", filename: "pine_warbler.webp" },
  { slug: "red_bellied_woodpecker", filename: "red_bellied_woodpecker.webp" },
  { slug: "red_tailed_hawk", filename: "red_tailed_hawk.webp" },
  { slug: "says_pheobe", filename: "says_pheobe.webp" },
  { slug: "silver_gull", filename: "silver_gull.webp" },
  { slug: "song_sparrow", filename: "song_sparrow.webp" },
  { slug: "spotted_shag", filename: "spotted_shag.webp" },
  { slug: "stellars_jay", filename: "stellars_jay.webp" },
  { slug: "takahe", filename: "takahe.webp" },
  { slug: "tufted_titmouse", filename: "tufted_titmouse.webp" },
  { slug: "turkey_vulture", filename: "turkey_vulture.webp" },
  { slug: "vermillion_flycatcher", filename: "vermillion_flycatcher.webp" },
  { slug: "white_breasted_nuthatch", filename: "white_breasted_nuthatch.webp" },
  { slug: "white_throated_sparrow", filename: "white_throated_sparrow.webp" },
  { slug: "yellow_bellied_sapsucker", filename: "yellow_bellied_sapsucker.webp" },
  { slug: "yellowhammer", filename: "yellowhammer.webp" },
] as const;

export const APP_CATALOG = [
  {
    slug: "australian_magpie",
    filename: "australian_magpie.webp",
    title: "Bill Splitter",
  },
  {
    slug: "pileated_woodpecker",
    filename: "pileated_woodpecker.webp",
    title: "Election App",
  },
  {
    slug: "eastern_bluebird",
    filename: "eastern_bluebird.webp",
    title: "Blackjack Trainer",
  },
  {
    slug: "mute_swan",
    filename: "mute_swan.webp",
    title: "Neck Stretch",
  },
] as const;

export type BirdSlug = (typeof BIRD_CATALOG)[number]["slug"];
export type AppSlug = (typeof APP_CATALOG)[number]["slug"];

export const BIRD_FILENAME_BY_SLUG: Record<BirdSlug, string> = BIRD_CATALOG.reduce(
  (acc, bird) => {
    acc[bird.slug] = bird.filename;
    return acc;
  },
  {} as Record<BirdSlug, string>
);
